baseurl: ""
url: "https://alex2017net.github.io"

theme_settings:
  title: ALEX
  email_address: alex_2017@foxmail.com
  description: 
    To tell a story

  #twitter_username: jekyllrb
  github_username:  alex_2017@git.zzz
  avatar: assets/img/triangle.svg
  favicon: assets/favicon.ico
  behance:  
  github: Alex2017net
  instagram:  
  linkedin:  


markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

#page
paginate: 5
paginate_path: "blog/page:num"


 # Localization strings
str_follow_on: "Follow on"
str_rss_follow: "Follow RSS feed"
str_email: "Email"
str_next_post: "Next post"
str_previous_post: "Previous post"
str_next_page: "Next"
str_previous_page: "Prev"
str_continue_reading: "Continue reading"
str_javascript_required_disqus: "Please enable JavaScript to view comments."

# Header and footer text
header_text:  #two or three lines to describe your site
     To Tell a Story 
header_text_feature_image: assets/img/pexels/triangular.jpeg
footer_text: 
   Powered by Jekyll with Bootstrap.
intro_text:
  I'm a designer.

collections:
  portfolio:
    output: true
    permalink: /:collection/:name



excerpt_separator:  '<!-- more -->'

home_slogan: to tell a story
